<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="MSM">
<meta name="dcterms.date" content="2026-09-21">

<title>Replication: The upside of down – Michael Schulte-Mecklenbeck</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-8ce484d92116c4accc59257505a5c3a2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-6YMRGKPWZY"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-6YMRGKPWZY');
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Michael Schulte-Mecklenbeck</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../_content/_pdf/CV_Index.pdf"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../research.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Replication: The upside of down</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Replication</div>
                <div class="quarto-category">Science</div>
                <div class="quarto-category">Decision Making</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>MSM </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">September 21, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="original-work" class="level1">
<h1>Original work</h1>
<p>Barone, M. J., Coulter, K. S., &amp; Li, X. (2020). <a href="https://doi.org/10.1016/j.jretai.2020.03.001">The upside of down: Presenting a price in a low or high location influences how consumers evaluate it</a>. <em>Journal of Retailing</em>, 96(3), 397-410.</p>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<blockquote class="blockquote">
<p>Can changing the vertical location of a price (e.g., presenting it above or below a product image in an advertisement or retail display) influence consumer response? Drawing from conceptual metaphor theory, we propose that a price’s vertical location can activate metaphors that relate vertical locations to magnitudinal concepts. These “down = less” and “up = more” metaphors can subsequently influence evaluations of a target price as being monetarily low or high in magnitude. Consistent with this premise, several lab and field investigations demonstrate that prices provided in low (vs.&nbsp;high) locations lead to lower price perceptions, more favorable purchase intentions, and higher in-store sales.</p>
</blockquote>
</section>
</section>
<section id="team-ba-autumn-2025" class="level1">
<h1>Team BA autumn 2025</h1>
<ul>
<li>Patrick Bargetze</li>
<li>Alina Bösiger</li>
<li>Sebastian Löpfe</li>
<li>Anastasiia Lykholai</li>
<li>Sarina Menning</li>
<li>Flavian Römer</li>
<li>Filip Stojanovic</li>
</ul>
</section>
<section id="the-idea" class="level1">
<h1>The idea</h1>
<p>Do we read a price the way we read a thermometer? Up means more, down means less. Barone and colleagues asked what happens when that metaphor is quietly attached to a price tag: put the same price <em>below</em> a product rather than <em>above</em> it, and the “down = less” association should make it feel like a smaller number. Nothing about the price changes – only where on the screen the number sits.</p>
<p>That is the entire manipulation. <a href="#fig-stimuli" class="quarto-xref">Figure&nbsp;1</a> shows one of our stimuli, the identical product at the identical price of CHF 7.00, in the two conditions participants could see.</p>
<div id="fig-stimuli" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stimuli-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-stimuli" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-stim-above" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-stim-above-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/stim_above.png" class="img-fluid figure-img" data-ref-parent="fig-stimuli">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-stim-above-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Price above the product
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-stimuli" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-stim-below" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-stim-below-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/stim_below.png" class="img-fluid figure-img" data-ref-parent="fig-stimuli">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-stim-below-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Price below the product
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stimuli-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The price location manipulation. Same product, same price, different vertical position.
</figcaption>
</figure>
</div>
<p>We replicated four of the original studies. Everyone saw all four, and was randomly assigned to a price location within each one. The three product studies were shown in a random order, with the metaphor questions always last:</p>
<ul>
<li><strong>Study 1a</strong> – no price is shown. Participants write down the price they think is appropriate, in an empty box placed either above or below the product image.</li>
<li><strong>Study 1b</strong> – a price is shown. Participants rate how low or high they find it (1 = very low, 9 = very high).</li>
<li><strong>Study 2</strong> – a price is shown. Participants rate how likely they would be to buy the product (1 = very unlikely, 9 = very likely).</li>
<li><strong>Study 5</strong> – no products. Participants report directly how strongly they hold the “up = more” and “down = less” associations.</li>
</ul>
<p>We crossed price location with product type in studies 1a, 1b and 2: five everyday products (cheese, toothpaste, instant coffee, a cleaning sponge, a power strip) and five luxury products (a Tesla, a Jura coffee machine, a cashmere jumper, Dior lip balm, a Roja diffuser). The original used a single product category per study, so the product factor is our addition – it lets us ask whether the effect survives across very different price ranges.</p>
<p>Because the three product studies were rotated, we can also check whether it matters <a href="#does-it-matter-when-a-study-appears">when</a> in the questionnaire a study appeared.</p>
<section id="how-we-analyse-this" class="level2">
<h2 class="anchored" data-anchor-id="how-we-analyse-this">How we analyse this</h2>
<p>Two features of the design decide the statistics, and both are easy to get wrong.</p>
<p>First, everyone answered five items per study, so the rows in our data are not independent – five of them belong to the same person. Treating them as independent would inflate the degrees of freedom roughly fivefold and shrink every <em>p</em> value with it. Every model below is therefore a linear mixed model with a random intercept per participant.</p>
<p>Second, product type has to be <em>in</em> the model rather than in front of it. Assignment was random but not stratified, so the two location conditions ended up with slightly different product mixes: in Study 1a, 53% of the estimates in the above condition were for luxury products against 45% in the below condition. Luxury items cost roughly twenty times more, so a few percentage points of composition difference is easily enough to fake a location effect. Testing location <em>adjusted for</em> product type removes that. The alternative – entering location first in a sequential (Type I) ANOVA – credits it with the imbalance and produces significant results that vanish the moment you control for what was actually being priced.</p>
<p>We report each effect as an <em>F</em> test with partial eta squared and its 95% confidence interval, plus the estimated marginal mean difference between the two locations, averaged over product type.</p>
</section>
</section>
<section id="sample" class="level1">
<h1>Sample</h1>
<p>We recruited through word of mouth among friends of the student group. 357 people opened the questionnaire. Of those, 284 answered at least one of the three attention checks correctly, and 219 of them also reached the end of the questionnaire. Those <strong>219 participants</strong> make up the analysed sample.</p>
<p>The attention checks were the usual instructed-response items – a question about the colour of the sun that asks you to tick “blue”, for instance. Requiring only one of three to be correct is a lenient rule, and it is the rule the original analysis used, so we kept it here rather than tightening it after the fact. It is worth knowing that it does most of its work in combination with the completion filter: of the 284 who passed a check, 65 dropped out before the end.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-demo" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-demo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Participants by gender.
</figcaption>
<div aria-describedby="tbl-demo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Gender</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Mean age</th>
<th style="text-align: right;">SD age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Female</td>
<td style="text-align: right;">138</td>
<td style="text-align: right;">35.4</td>
<td style="text-align: right;">15.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Male</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">33.0</td>
<td style="text-align: right;">14.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Non-binary</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">82.0</td>
<td style="text-align: right;">24.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The sample is skewed toward female and young (<a href="#tbl-demo" class="quarto-xref">Table&nbsp;1</a>). The three non-binary participants are too few to interpret on their own, and their mean age is pulled around by a single very old respondent.</p>
</section>
<section id="study-1a-estimating-a-price-from-scratch" class="level1">
<h1>Study 1a – estimating a price from scratch</h1>
<p>Participants saw a product with an empty box either above or below it, and wrote in the price they considered appropriate. If “down = less” is doing any work, the estimates written into a low box should come out smaller.</p>
<p>Free-text prices are messy. Ours ranged from CHF 0 to CHF 4,500,000, and the standard deviation in the luxury condition (198,120) is an order of magnitude larger than the mean (<a href="#tbl-1a-raw" class="quarto-xref">Table&nbsp;2</a>). A handful of people valuing the Tesla at several million francs is enough to swamp everything else.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-1a-raw" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-1a-raw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Study 1a: raw price estimates in CHF.
</figcaption>
<div aria-describedby="tbl-1a-raw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Position</th>
<th style="text-align: left;">Product</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">above</td>
<td style="text-align: left;">Everyday product</td>
<td style="text-align: right;">265</td>
<td style="text-align: right;">27.1</td>
<td style="text-align: right;">130.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">above</td>
<td style="text-align: left;">Luxury product</td>
<td style="text-align: right;">295</td>
<td style="text-align: right;">28324.9</td>
<td style="text-align: right;">265566.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">below</td>
<td style="text-align: left;">Everyday product</td>
<td style="text-align: right;">293</td>
<td style="text-align: right;">16.4</td>
<td style="text-align: right;">32.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">below</td>
<td style="text-align: left;">Luxury product</td>
<td style="text-align: right;">239</td>
<td style="text-align: right;">9643.6</td>
<td style="text-align: right;">24298.8</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The original paper hit the same problem and log-transformed the estimates, so we do the same. On the log scale a franc difference counts the same whether it sits on a tube of toothpaste or on a car.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-1a" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="staticfig-1a-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Study 1a: estimated price by price location and product type. Mean with 95% CI, log scale.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-1a-log" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-1a-log-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Study 1a: geometric means of the price estimates.
</figcaption>
<div aria-describedby="tbl-1a-log-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Position</th>
<th style="text-align: left;">Product</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Mean (CHF)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">above</td>
<td style="text-align: left;">Everyday product</td>
<td style="text-align: right;">264</td>
<td style="text-align: right;">10.10</td>
</tr>
<tr class="even">
<td style="text-align: left;">above</td>
<td style="text-align: left;">Luxury product</td>
<td style="text-align: right;">294</td>
<td style="text-align: right;">230.15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">below</td>
<td style="text-align: left;">Everyday product</td>
<td style="text-align: right;">290</td>
<td style="text-align: right;">9.52</td>
</tr>
<tr class="even">
<td style="text-align: left;">below</td>
<td style="text-align: left;">Luxury product</td>
<td style="text-align: right;">236</td>
<td style="text-align: right;">200.31</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#fig-1a" class="quarto-xref">Figure&nbsp;2</a> and <a href="#tbl-1a-log" class="quarto-xref">Table&nbsp;3</a> show estimates that are a shade lower in the below condition for both product types, which is the direction the original predicts. The test does not back it up: <em>F</em>(1, 1081) = 0.53, <em>p = .465</em>, <span class="math inline">\(\eta^2_p\)</span> = .000, 95% CI [.000, .007]. The estimated difference is -9.3%, 95% CI [-30.3%, +18.0%] – prices in a low box come out lower on average, but the interval comfortably contains zero and both plausible directions. Product type, by contrast, does what you would expect of it (<em>F</em>(1, 1081) = 533.99, <em>p &lt; .001</em>, <span class="math inline">\(\eta^2_p\)</span> = .331, 95% CI [.288, .372]); people know a Tesla costs more than toothpaste.</p>
<p><strong>Study 1a does not replicate.</strong></p>
</section>
<section id="study-1b-judging-a-price-that-is-shown" class="level1">
<h1>Study 1b – judging a price that is shown</h1>
<p>Here the price was given and participants rated how low or high it felt. This is the most direct test of the original claim, and the one where we expected the clearest answer.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-1b" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="staticfig-1b-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Study 1b: perceived price magnitude by price location and product type. Mean with 95% CI (1 = very low, 9 = very high).
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-1b" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-1b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Study 1b: perceived price magnitude.
</figcaption>
<div aria-describedby="tbl-1b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Position</th>
<th style="text-align: left;">Product</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">above</td>
<td style="text-align: left;">Everyday product</td>
<td style="text-align: right;">225</td>
<td style="text-align: right;">5.72</td>
<td style="text-align: right;">1.96</td>
</tr>
<tr class="even">
<td style="text-align: left;">above</td>
<td style="text-align: left;">Luxury product</td>
<td style="text-align: right;">265</td>
<td style="text-align: right;">7.25</td>
<td style="text-align: right;">1.98</td>
</tr>
<tr class="odd">
<td style="text-align: left;">below</td>
<td style="text-align: left;">Everyday product</td>
<td style="text-align: right;">219</td>
<td style="text-align: right;">5.70</td>
<td style="text-align: right;">1.84</td>
</tr>
<tr class="even">
<td style="text-align: left;">below</td>
<td style="text-align: left;">Luxury product</td>
<td style="text-align: right;">285</td>
<td style="text-align: right;">7.38</td>
<td style="text-align: right;">2.09</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Nothing, and this time not even a hint of a direction. The two locations land on top of each other for everyday products (5.72 versus 5.70) and, if anything, the low price is rated <em>higher</em> for luxury products (7.25 versus 7.38), which runs against the prediction (<a href="#fig-1b" class="quarto-xref">Figure&nbsp;3</a>, <a href="#tbl-1b" class="quarto-xref">Table&nbsp;4</a>). The model agrees: <em>F</em>(1, 222.8) = 0.13, <em>p = .721</em>, <span class="math inline">\(\eta^2_p\)</span> = .001, 95% CI [.000, .022], an estimated difference of +0.06, 95% CI [-0.29, +0.41] on the nine-point scale. The product manipulation meanwhile works exactly as expected (<em>F</em>(1, 224.2) = 79.48, <em>p &lt; .001</em>, <span class="math inline">\(\eta^2_p\)</span> = .262, 95% CI [.170, .352]) – so the measure is clearly sensitive, just not to price location.</p>
<p>The original reports a significant effect here (<em>F</em>(1, 203) = 4.36, <em>p</em> = .04) on a sample half the size of ours. We have power on our side and we do not find the effect.</p>
<p><strong>Study 1b does not replicate.</strong></p>
</section>
<section id="study-2-purchase-intention" class="level1">
<h1>Study 2 – purchase intention</h1>
<p>Same setup as 1b, but participants rated how likely they would be to buy rather than how expensive it looked. The original argued that a price which feels smaller should translate into stronger intentions to buy.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="staticfig-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Study 2: purchase intention by price location and product type. Mean with 95% CI (1 = very unlikely, 9 = very likely).
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-2" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Study 2: purchase intention.
</figcaption>
<div aria-describedby="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Position</th>
<th style="text-align: left;">Product</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">above</td>
<td style="text-align: left;">Everyday product</td>
<td style="text-align: right;">255</td>
<td style="text-align: right;">4.87</td>
<td style="text-align: right;">2.89</td>
</tr>
<tr class="even">
<td style="text-align: left;">above</td>
<td style="text-align: left;">Luxury product</td>
<td style="text-align: right;">268</td>
<td style="text-align: right;">1.75</td>
<td style="text-align: right;">1.60</td>
</tr>
<tr class="odd">
<td style="text-align: left;">below</td>
<td style="text-align: left;">Everyday product</td>
<td style="text-align: right;">279</td>
<td style="text-align: right;">5.10</td>
<td style="text-align: right;">2.85</td>
</tr>
<tr class="even">
<td style="text-align: left;">below</td>
<td style="text-align: left;">Luxury product</td>
<td style="text-align: right;">265</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">2.11</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>This is the closest we come. Participants were somewhat more willing to buy when the price sat below the product, for everyday products (4.87 versus 5.10) and luxury products (1.75 versus 2.00) alike (<a href="#fig-2" class="quarto-xref">Figure&nbsp;4</a>, <a href="#tbl-2" class="quarto-xref">Table&nbsp;5</a>). The estimated difference, +0.24, 95% CI [-0.18, +0.65] on the nine-point scale, runs in the predicted direction and is the largest of the three studies, but the interval still includes zero and the test is not significant: <em>F</em>(1, 215.9) = 1.25, <em>p = .266</em>, <span class="math inline">\(\eta^2_p\)</span> = .006, 95% CI [.000, .042].</p>
<p>That is worth being precise about. A consistent direction across two product categories is the kind of thing that makes you want to believe an effect is there, and it may well be – our interval is compatible with an effect of up to two thirds of a scale point. It is also compatible with nothing at all, and with a small effect in the opposite direction. This study does not settle the question.</p>
<p>The low purchase intentions for luxury products most likely goes back to our sample of students - being asked whether they would buy a Tesla; a mean of about 2 on a 9-point scale is a statement about budgets rather than about design.</p>
<p><strong>Study 2 does not replicate.</strong></p>
</section>
<section id="study-5-do-people-hold-the-metaphor-at-all" class="level1">
<h1>Study 5 – do people hold the metaphor at all?</h1>
<p>The whole account rests on people associating up with more and down with less. Study 5 measures that directly, with four statements rated from 1 to 9. The first two ask what “up” and “down” bring to mind (1 = less of something, 9 = more of something); the last two ask for agreement that a lower position means less and a higher position means more.</p>
<p>Because every participant answered all four statements, these are within-person comparisons, and the mixed model uses that pairing.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-5" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="staticfig-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Study 5: strength of the vertical metaphor across the four statements. Mean with 95% CI.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-5" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Study 5: metaphor strength.
</figcaption>
<div aria-describedby="tbl-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">“Up” means more</td>
<td style="text-align: right;">203</td>
<td style="text-align: right;">7.21</td>
<td style="text-align: right;">1.76</td>
</tr>
<tr class="even">
<td style="text-align: left;">“Down” means less</td>
<td style="text-align: right;">190</td>
<td style="text-align: right;">2.77</td>
<td style="text-align: right;">1.87</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Higher = more</td>
<td style="text-align: right;">196</td>
<td style="text-align: right;">7.03</td>
<td style="text-align: right;">2.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lower = less</td>
<td style="text-align: right;">202</td>
<td style="text-align: right;">6.33</td>
<td style="text-align: right;">2.51</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The metaphor is there, and unlike everything above it is not in doubt (<a href="#fig-5" class="quarto-xref">Figure&nbsp;5</a>, <a href="#tbl-5" class="quarto-xref">Table&nbsp;6</a>). “Up” sits at 7.21 and “down” at 2.77 on the same scale, a gap of 4.44, 95% CI [4.08, 4.80] on the nine-point scale (<em>F</em>(1, 391) = 590.08, <em>p &lt; .001</em>, <span class="math inline">\(\eta^2_p\)</span> = .601, 95% CI [.546, .649]). Asked directly, people also agree that higher means more (7.03) more strongly than that lower means less (6.33), a smaller but reliable gap of 0.68, 95% CI [0.33, 1.04] (<em>F</em>(1, 198.1) = 14.43, <em>p &lt; .001</em>, <span class="math inline">\(\eta^2_p\)</span> = .068, 95% CI [.016, .145]).</p>
<p>So the central ingredient the theory needs is present in our sample, at full strength. What does not follow is the behaviour it is supposed to produce.</p>
</section>
<section id="does-it-matter-when-a-study-appears" class="level1">
<h1>Does it matter when a study appears?</h1>
<p>Studies 1a, 1b and 2 were rotated, so each one landed first, second or third for roughly a third of participants. That gives us a free check on something replications rarely get to look at: whether the position of a study inside the questionnaire changes what it finds.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-order" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-order-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="staticfig-order-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-order-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Answers by the position a study occupied in the questionnaire. Mean with 95% CI, collapsed across product type. Study 1a is on the log scale.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-order" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-order-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Task order added to each model.
</figcaption>
<div aria-describedby="tbl-order-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 40%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Study</th>
<th style="text-align: left;">Effect of order</th>
<th style="text-align: left;">Location x order</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1a – price estimation</td>
<td style="text-align: left;">F(1, 1079) = 0.70, p = .401, η²p = .001 [.000, .007]</td>
<td style="text-align: left;">F(1, 1079) = 0.82, p = .366, η²p = .001 [.000, .008]</td>
</tr>
<tr class="even">
<td style="text-align: left;">1b – price magnitude</td>
<td style="text-align: left;">F(1, 221.1) = 1.28, p = .259, η²p = .006 [.000, .041]</td>
<td style="text-align: left;">F(1, 221.0) = 0.71, p = .400, η²p = .003 [.000, .034]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2 – purchase intention</td>
<td style="text-align: left;">F(1, 213.2) = 8.50, p = .004, η²p = .038 [.004, .101]</td>
<td style="text-align: left;">F(1, 213.5) = 0.52, p = .472, η²p = .002 [.000, .032]</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Two things fall out of <a href="#fig-order" class="quarto-xref">Figure&nbsp;6</a> and <a href="#tbl-order" class="quarto-xref">Table&nbsp;7</a>.</p>
<p>The first is that order matters in Study 2. Purchase intentions were markedly lower when Study 2 came first than when it came later (<em>F</em>(1, 213.2) = 8.50, <em>p = .004</em>, <span class="math inline">\(\eta^2_p\)</span> = .038, 95% CI [.004, .101]). Studies 1a and 1b show nothing of the sort (<em>F</em>(1, 1079) = 0.70, <em>p = .401</em>, <span class="math inline">\(\eta^2_p\)</span> = .001, 95% CI [.000, .007] and <em>F</em>(1, 221.1) = 1.28, <em>p = .259</em>, <span class="math inline">\(\eta^2_p\)</span> = .006, 95% CI [.000, .041]). The most likely reading is warm-up: participants who had already worked through a block of prices had a rough sense of what these products cost, and answered the buying question less conservatively than those who met the Tesla cold.</p>
<p>The second is that order does <em>not</em> interact with price location in any of the three studies (all <em>p</em> &gt; .36). Whatever the rotation is doing to the overall level of responses, it is doing it equally to the above and below conditions. So the rotation is neither creating nor concealing a location effect – the nulls above are not an artefact of when people saw what.</p>
<p>Worth keeping in mind if you run something like this yourself. A rotation costs nothing and buys you the ability to tell “my effect” apart from “my questionnaire”.</p>
</section>
<section id="where-that-leaves-us" class="level1">
<h1>Where that leaves us</h1>
<div class="cell" data-layout-align="center">
<div id="tbl-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Original findings and our replication.
</figcaption>
<div aria-describedby="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 21%">
<col style="width: 45%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Study</th>
<th style="text-align: left;">Original</th>
<th style="text-align: left;">Replication</th>
<th style="text-align: left;">Outcome</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1a – price estimation</td>
<td style="text-align: left;">F(2, 88) = 3.55, p = .03</td>
<td style="text-align: left;">F(1, 1081) = 0.53, p = .465, η²p = .000 [.000, .007]</td>
<td style="text-align: left;">not replicated</td>
</tr>
<tr class="even">
<td style="text-align: left;">1b – price magnitude</td>
<td style="text-align: left;">F(1, 203) = 4.36, p = .04</td>
<td style="text-align: left;">F(1, 222.8) = 0.13, p = .721, η²p = .001 [.000, .022]</td>
<td style="text-align: left;">not replicated</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2 – purchase intention</td>
<td style="text-align: left;">F(2, 86) = 4.14, p = .02</td>
<td style="text-align: left;">F(1, 215.9) = 1.25, p = .266, η²p = .006 [.000, .042]</td>
<td style="text-align: left;">not replicated</td>
</tr>
<tr class="even">
<td style="text-align: left;">5 – metaphor strength</td>
<td style="text-align: left;">held by participants</td>
<td style="text-align: left;">F(1, 391) = 590.08, p &lt; .001, η²p = .601 [.546, .649]</td>
<td style="text-align: left;">replicated</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-summary" class="quarto-xref">Table&nbsp;8</a> is not the result we expected when we started. People in our sample hold the “up = more, down = less” metaphor about as strongly as it is possible to hold anything on a nine-point scale. It simply does not travel to their prices. Estimating a price from scratch, judging a price on the page, deciding whether to buy – in all three the confidence interval for the location effect straddles zero.</p>
<p>The direction is not random, for what that is worth. Two of the three point the way the original predicted, and Study 2’s difference of about a quarter of a scale point is the sort of effect the original was describing. With 219 participants we could not separate it from noise, and an effect that needs more than this to show itself is not the effect the original reported.</p>
<p>Caveats. Our design differs from the original: we ran all four studies on the same participants rather than using a fresh sample for each, we recruited a Swiss convenience sample rather than US students and mTurk workers (although you probably would not want to do that anyway today), and we added a product-type factor the original did not have. Any of those could explain why we see nothing where the original saw something. The rotation at least lets us rule out running order as the culprit.</p>
<p>Price location may still do something. On this evidence, whatever it does is smaller than a study of this size can see.</p>
</section>
<section id="data" class="level1">
<h1>Data</h1>
<p>The anonymised responses behind every figure and table on this page are in <a href="https://github.com/schulte-mecklenbeck/web20/blob/main/0_data/BAHS2025_public.csv"><code>BAHS2025_public.csv</code></a>: one row per answer, with the participant’s random <code>ID</code>, the <code>study</code>, the price <code>position</code>, the product type (<code>price</code>: A for everyday, L for luxury), the item (<code>level</code>), the serial position of that study in the questionnaire (<code>order</code>) and the <code>answers</code> themselves. Gender and age are held back and are not published.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Michael Schulte-Mecklenbeck</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>