project:
  type: website
  output-dir: docs

website:
  title: "Michael Schulte-Mecklenbeck"
  navbar:
    right:
      - text: 'Blog'
        file: 'index.qmd'
      - about.qmd
      - text: 'CV'
        file: '_content/CV_Index.pdf'
      - text: 'Publications'
        file: 'research.qmd'
  page-footer: 2023 Michael Schulte-Mecklenbeck

format:
  html:
    include-in-header: "gtag.js"
    theme: spacelab
    css: styles.css

editor: source
