<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="MSM">
<meta name="dcterms.date" content="2026-01-21">

<title>Replication: Fortune favors the bold – Michael Schulte-Mecklenbeck</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-8ce484d92116c4accc59257505a5c3a2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-6YMRGKPWZY"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-6YMRGKPWZY');
</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Michael Schulte-Mecklenbeck</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../_content/_pdf/CV_Index.pdf"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../research.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Replication: Fortune favors the bold</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Replication</div>
                <div class="quarto-category">Science</div>
                <div class="quarto-category">Learning</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>MSM </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 21, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="cell" data-layout-align="center">
<style type="text/css">
.stim {
  border: 1px solid #d0d0d0;
  border-radius: 6px;
  padding: 0.8em 1.2em;
  margin-bottom: 1em;
  background: #fbfbfb;
}
.stim .cap {
  font-family: inherit;
  font-size: 0.8em;
  font-weight: 600;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: #777;
  margin-bottom: 0.4em;
}
.stim ul { margin: 0; }
.plain    { font-family: Arial, Helvetica, sans-serif; color: #000; }
.hardfont { font-family: Haettenschweiler, Impact, "Arial Narrow", sans-serif;
            font-style: italic; color: #999; }
.digits   { font-family: Arial, Helvetica, sans-serif; color: #000; }
.gaps     { font-family: Arial, Helvetica, sans-serif; color: #000; }
</style>
</div>
<section id="original-work" class="level1">
<h1>Original work</h1>
<p>Diemand-Yauman, C., Oppenheimer, D. M., &amp; Vaughan, E. B. (2011). <a href="https://doi.org/10.1016/j.cognition.2010.09.012">Fortune favors the bold (and the Italicized): Effects of disfluency on educational outcomes</a>. <em>Cognition</em>, 118(1), 111-115.</p>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<blockquote class="blockquote">
<p>Previous research has shown that disfluency – the subjective experience of difficulty associated with cognitive operations – leads to deeper processing. Two studies explore the extent to which this deeper processing engendered by disfluency interventions can lead to improved memory performance. Study 1 found that information in hard-to-read fonts was better remembered than easier to read information in a controlled laboratory setting. Study 2 extended this finding to high school classrooms. The results suggest that superficial changes to learning materials could yield significant improvements in educational outcomes.</p>
</blockquote>
</section>
</section>
<section id="team-ba-spring-2025" class="level1">
<h1>Team BA spring 2025</h1>
<ul>
<li>Wadija Ali Ebrahim</li>
<li>Noah Born</li>
<li>Nina Burki</li>
<li>Alain Gehri</li>
<li>Nando Kolb</li>
<li>Tina Loretan</li>
<li>Sebastian Pfäffli</li>
<li>Nhat Ngan Phan</li>
<li>Noemi Righetti</li>
<li>Anja Saner</li>
<li>Luca Schellinger</li>
<li>Alexandra Tellenbach</li>
</ul>
</section>
<section id="the-idea" class="level1">
<h1>The idea</h1>
<p>Make a text slightly harder to read and people will remember more of it. That is the claim and it is wonderfully cheap. Diemand-Yauman and colleagues had participants learn the features of three invented alien species, printed either in clean 16-point Arial or in a small grey hard-to-read font. Fifteen minutes and a distraction task later, the hard-font group recalled 86.5% of the tested features and the clean-font group 72.8% – fourteen percentage points, from nothing more than a typographic nuisance.</p>
<p>The mechanism is supposed to be metacognitive. Struggling slightly to decode the words signals that you have not mastered the material, and that signal recruits the slower, more elaborative processing that makes things stick. A <em>desirable difficulty</em>, in Bjork’s phrase.</p>
<p>If that is really what is going on, then the specific nuisance should not matter much. So we replicated the original font manipulation and added three more ways of making the same material harder to take in.</p>
<p>Everyone learned the same three alien species – the Pangerisch, the Norgletti and the Derlenga, seven features each – and was randomly assigned to one of six presentation formats.</p>
<div class="stim">
<div class="cap">
<p>Text, plain – the control</p>
</div>
<div class="plain">
<p><strong>Der Norgletti</strong></p>
<ul>
<li>60 cm gross</li>
<li>Ernährt sich von Blütenblättern und Pollen</li>
<li>Hat ein einzelnes gelbes Horn auf dem Kopf</li>
</ul>
</div>
</div>
<div class="stim">
<div class="cap">
<p>Text, hard font – the original manipulation</p>
</div>
<div class="hardfont">
<p><strong>Der Norgletti</strong></p>
<ul>
<li>60 cm gross</li>
<li>Ernährt sich von Blütenblättern und Pollen</li>
<li>Hat ein einzelnes gelbes Horn auf dem Kopf</li>
</ul>
</div>
</div>
<div class="stim">
<div class="cap">
<p>Text, digits – letters replaced by look-alike numbers</p>
</div>
<div class="digits">
<p><strong>D3R N0RGL3TT1</strong></p>
<ul>
<li>60 Z3NT1M3T3R 6R0SS</li>
<li>3RNÄHRT 51CH V0N BLÜT3NBLÄTT3RN UND P0LL3N</li>
<li>H4T 31N 31NZ3LN35 63LB3S H0RN 4UF D3M K0PF</li>
</ul>
</div>
</div>
<div class="stim">
<div class="cap">
<p>Text, gaps – letters deleted</p>
</div>
<div class="gaps">
<p><strong>Der Norgletti</strong></p>
<ul>
<li>60 Z_ntim_t_r gr_ss</li>
<li>Ern_hrt sich von B_ütenbl_tt_rn und P_llen</li>
<li>Hat ein e_nzel_es g_lbes Ho_n auf dem Ko_f</li>
</ul>
</div>
</div>
<p>The two remaining conditions moved the same content from the eyes to participant’s ears: a <strong>clear audio</strong> recording of the species descriptions, and a <strong>distorted audio</strong> version of the same recording.</p>
<p>After the learning phase a set of filler tasks was introduced – mood ratings, a questionnaire, a sentence task, a word-sorting task – these tasks ran for about fifteen minutes, as in the original. The memory test followed: seven open questions about the aliens’ features, answered by typing rather than choosing, and scored by hand afterwards. Three parallel question sets existed and each participant was given one of them at random, so no single feature carried the whole result.</p>
<p>We added two questionnaires suggested by the disfluency literature: Dweck’s three-item ‘mindset scale’, and the 17-item ‘Need for Cognition’ scale. If effortful processing is the engine, people who enjoy effortful thinking or who believe ability is malleable are the obvious candidates for a larger effect.</p>
</section>
<section id="sample" class="level1">
<h1>Sample</h1>
<p>The questionnaire was distributed through the students’ own networks – fellow students, friends, family. 198 people opened it and 113 reached the end.</p>
<p>We excluded 18 of those: participants who failed <strong>both</strong> embedded attention checks, who reported uncorrected vision problems (the study is about reading), or who did not report German at C1 or C2 level. That leaves <strong>95 participants</strong> in the analysed sample. Requiring only one of the two attention checks to be correct is a lenient rule.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-demo" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-demo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Participants by gender.
</figcaption>
<div aria-describedby="tbl-demo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Gender</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Mean age</th>
<th style="text-align: right;">SD age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Female</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">31.5</td>
<td style="text-align: right;">14.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Male</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">29.5</td>
<td style="text-align: right;">13.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Non-binary</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">24.0</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-cond" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cond-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Participants per condition.
</figcaption>
<div aria-describedby="tbl-cond-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Condition</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Mean age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Text, plain</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">25.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Text, hard font</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">34.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Text, digits</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">33.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Text, gaps</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">24.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Audio, clear</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">33.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Audio, distorted</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">31.9</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The sample is a convenience sample, wider in age than a student pool (mean 30.6 years, SD 13.7) and rather small once it is split six ways: between 13 and 20 people per condition.</p>
</section>
<section id="does-a-hard-font-help-you-remember" class="level1">
<h1>Does a hard font help you remember?</h1>
<p>The memory score is simply the proportion of the seven questions a participant answered correctly. Answers were coded by hand, so “Pollen und Blüten” counts as a hit even though it is not word for word what the text said; a question left blank counts as not recalled.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-text" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-text-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="staticfig-text-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-text-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Recall after a fifteen-minute delay in the two conditions that replicate the original experiment: plain Arial against the hard-to-read font.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-text" class="quarto-xref">Figure&nbsp;1</a> puts the two conditions that mirror the original side by side. Participants who read the plain Arial version recalled 65.9% of the features; participants who read the hard-font version recalled 59.8%. The difference is 6.1 percentage points, it points the wrong way, and it is nowhere near significant (<em>t</em>(26.0) = -0.52, <em>p</em> = .607, <em>d</em> = -0.19). The 95% confidence interval runs from -30.3 to 18.0 percentage points – wide enough to contain the original’s +14, which is the honest way to put it: this comparison, on its own, cannot rule the original effect out.</p>
<p><strong>The font effect does not replicate.</strong></p>
</section>
<section id="the-three-other-ways-of-making-it-hard" class="level1">
<h1>The three other ways of making it hard</h1>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-all" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-all-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="staticfig-all-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-all-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Recall after a fifteen-minute delay in all six conditions, split by whether the material was read or heard.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-all" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-all-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Recall by condition.
</figcaption>
<div aria-describedby="tbl-all-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Condition</th>
<th style="text-align: right;">n</th>
<th style="text-align: left;">Mean</th>
<th style="text-align: left;">SD</th>
<th style="text-align: left;">95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Text, plain</td>
<td style="text-align: right;">13</td>
<td style="text-align: left;">65.9%</td>
<td style="text-align: left;">31.2%</td>
<td style="text-align: left;">[47.1%, 84.8%]</td>
</tr>
<tr class="even">
<td style="text-align: left;">Text, hard font</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;">59.8%</td>
<td style="text-align: left;">31.8%</td>
<td style="text-align: left;">[42.9%, 76.8%]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Text, digits</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;">53.6%</td>
<td style="text-align: left;">33.7%</td>
<td style="text-align: left;">[37.8%, 69.3%]</td>
</tr>
<tr class="even">
<td style="text-align: left;">Text, gaps</td>
<td style="text-align: right;">17</td>
<td style="text-align: left;">59.7%</td>
<td style="text-align: left;">34.3%</td>
<td style="text-align: left;">[42.0%, 77.3%]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Audio, clear</td>
<td style="text-align: right;">14</td>
<td style="text-align: left;">51.0%</td>
<td style="text-align: left;">33.5%</td>
<td style="text-align: left;">[31.7%, 70.4%]</td>
</tr>
<tr class="even">
<td style="text-align: left;">Audio, distorted</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">44.8%</td>
<td style="text-align: left;">35.4%</td>
<td style="text-align: left;">[25.2%, 64.3%]</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#fig-all" class="quarto-xref">Figure&nbsp;2</a> adds the four conditions the original never ran. Nothing separates the six groups (<em>F</em>(5, 89) = 0.73, <em>p</em> = .601, η²<sub>p</sub> = .040). The digits version (53.6%) and the gap version (59.7%) sit right where the plain text sits. Distorted audio (44.8%) is the weakest condition of all and clear audio (51.0%) is not much better, but the two do not differ reliably either (<em>t</em>(27.0) = -0.49, <em>p</em> = .628, <em>d</em> = -0.18).</p>
<p>Pooling all four disfluent conditions against the two fluent ones gives the comparison the most statistical room: 54.6% versus 58.2%, a difference of 3.6 percentage points in the wrong direction (<em>t</em>(49.0) = -0.48, <em>p</em> = .635, <em>d</em> = -0.11, 95% CI [-18.6, 11.5] percentage points). With 68 disfluent and 27 fluent participants, that test had a 97% chance of catching an effect the size of the original one (<em>d</em> = 0.87). It caught nothing.</p>
<p>The only hint of a difference is between the eye and the ear: text conditions beat audio conditions by a margin that is suggestive rather than reliable (<em>F</em>(1, 54) = 2.97, <em>p</em> = .091, η²<sub>p</sub> = .052 in a fluency × modality ANOVA on the four conditions that have a fluent and a disfluent version), with no trace of a fluency effect (<em>F</em>(1, 54) = 0.51, <em>p</em> = .480, η²<sub>p</sub> = .009) and no interaction (<em>F</em>(1, 54) = 0.00, <em>p</em> = .993, η²<sub>p</sub> = .000).</p>
</section>
<section id="did-the-manipulations-land" class="level1">
<h1>Did the manipulations land?</h1>
<p>A null result is only interesting if the manipulation did something. We asked everyone afterwards how hard the material had been to take in, and how hard it had been to learn, both on a five-point scale.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-mc" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="staticfig-mc-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Manipulation check: how hard the material was to take in (left panel) and how hard the information was to learn (right panel), rated on a five-point scale from 1 = very easy to 5 = very hard.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The conditions did differ in how hard they felt (<em>F</em>(5, 88) = 4.09, <em>p</em> = .002, η²<sub>p</sub> = .189; left panel of <a href="#fig-mc" class="quarto-xref">Figure&nbsp;3</a>), but not in the way the design intended. Distorted audio was clearly harder than clear audio (3.27 versus 2.07, <em>t</em>(26.7) = 3.28, <em>p</em> = .003, <em>d</em> = 1.22), and the digits version was harder than plain text (2.79 versus 2.23, <em>t</em>(27.3) = 2.07, <em>p</em> = .048, <em>d</em> = 0.73). The hard font, on the other hand, barely registered (2.44 versus 2.23, <em>t</em>(24.0) = 0.81, <em>p</em> = .426, <em>d</em> = 0.31), and neither did the gaps (2.29, <em>t</em>(28.0) = 0.21, <em>p</em> = .834, <em>d</em> = 0.08).</p>
<p>That cuts both ways. The original authors stress that their manipulation is subtle – a reader who never sees the fluent version is “unlikely to be even consciously aware of the added difficulty”. A font that does not feel harder is exactly what they describe, so a flat manipulation check is not by itself evidence that nothing happened. But it does mean that in our version of the study, the two conditions that <em>were</em> felt as harder are also the two that produced no memory benefit whatsoever. Difficulty that participants notice is not doing the work here.</p>
<p>The right-hand panel of <a href="#fig-mc" class="quarto-xref">Figure&nbsp;3</a> adds something the recall data only hinted at. Both audio conditions – the clear recording as much as the distorted one – were rated as harder to <em>learn</em> from than any of the four text conditions (3.71 and 3.67 against 3.00 for plain text). Listening once to a spoken list is simply a worse way to memorise it than reading it, and that shows up in both the ratings and the recall.</p>
<p>Asked directly whether the presentation format had affected their ability to take the material in, 67 of 94 said yes – in every condition, including the plain one.</p>
</section>
<section id="mindset-and-need-for-cognition" class="level1">
<h1>Mindset and need for cognition</h1>
<p>Mindset scores are unrelated to how much people recalled (<em>r</em> = -.11, 95% CI [-.31, .09], <em>p</em> = .281), and so is Need for Cognition (<em>r</em> = .02, 95% CI [-.19, .22], <em>p</em> = .885). More to the point, neither moderates the effect of disfluency: the interaction term is not significant for mindset (<em>F</em>(1, 91) = 2.11, <em>p</em> = .150, η²<sub>p</sub> = .023) or for Need for Cognition (<em>F</em>(1, 91) = 0.05, <em>p</em> = .821, η²<sub>p</sub> = .001). There is no subgroup in this sample for whom the hard font paid off.</p>
</section>
<section id="where-that-leaves-us" class="level1">
<h1>Where that leaves us</h1>
<div class="cell" data-layout-align="center">
<div id="tbl-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Original finding and our replication.
</figcaption>
<div aria-describedby="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 33%">
<col style="width: 36%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">Original</th>
<th style="text-align: left;">Replication</th>
<th style="text-align: left;">Outcome</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Hard font vs.&nbsp;plain text</td>
<td style="text-align: left;">86.5% vs.&nbsp;72.8%, t(26) = 2.3, p &lt; .05, d = 0.87</td>
<td style="text-align: left;">59.8% vs.&nbsp;65.9%, t(26.0) = -0.52, p = .61, d = -0.19</td>
<td style="text-align: left;">not replicated</td>
</tr>
<tr class="even">
<td style="text-align: left;">Digits vs.&nbsp;plain text</td>
<td style="text-align: left;">not tested</td>
<td style="text-align: left;">53.6% vs.&nbsp;65.9%</td>
<td style="text-align: left;">no effect</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gaps vs.&nbsp;plain text</td>
<td style="text-align: left;">not tested</td>
<td style="text-align: left;">59.7% vs.&nbsp;65.9%</td>
<td style="text-align: left;">no effect</td>
</tr>
<tr class="even">
<td style="text-align: left;">Distorted vs.&nbsp;clear audio</td>
<td style="text-align: left;">not tested</td>
<td style="text-align: left;">44.8% vs.&nbsp;51.0%, t(27.0) = -0.49, p = .63, d = -0.18</td>
<td style="text-align: left;">no effect</td>
</tr>
<tr class="odd">
<td style="text-align: left;">All disfluent vs.&nbsp;all fluent</td>
<td style="text-align: left;">not tested</td>
<td style="text-align: left;">54.6% vs.&nbsp;58.2%, t(49.0) = -0.48, p = .63, d = -0.11</td>
<td style="text-align: left;">no effect</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Four ways of making the same material harder to absorb, and not one of them improved recall. That is a clean result, and it is worth being clear about how strong a claim it supports.</p>
<p>The single comparison that mirrors the original – hard font against plain text, 16 against 13 participants – is underpowered. With groups that size we had a 61% chance of detecting an effect as large as the one the original reports, so a null there is weak evidence on its own. The pooled comparison is a different matter: 68 disfluent participants against 27 fluent ones, a design with ample power for an effect of that size, and what it found was 3.6 percentage points pointing the other way.</p>
<p>This is also where the broader literature has landed: Rummer, Schweppe and Schwede ran three modified replications of exactly this experiment <a href="https://doi.org/10.1007/s11409-015-9151-5">Fortune is fickle: null-effects of disfluency on learning outcomes</a> (<em>Metacognition and Learning</em>, 2016). A meta-analysis of 25 studies with 3135 participants by Xie, Zhou and Liu found <a href="https://doi.org/10.1007/s10648-018-9442-x">no effect of perceptual disfluency on recall</a> (<em>d</em> = -0.01) or transfer, but a clear effect on how well people <em>thought</em> they had learned and on how long they spent trying – though that meta-analysis has itself been <a href="https://doi.org/10.1007/s10648-020-09579-1">criticised for coding errors</a>.</p>
<p>What we can add is that the failure is not specific to fonts. Digits in place of letters, missing letters, a degraded recording – the disfluency idea predicts a benefit from all of them, and none appeared, not even among the people who like to think hard or believe that ability is trainable. Meanwhile the two manipulations participants did report as harder are also the two disfluent conditions with the lowest recall. Desirable difficulty appears to be a narrow target, and merely making things annoying does not hit it.</p>
<p>Caveats. Our sample is a convenience sample spread thin across six conditions, so each individual cell is small. The learning material was translated into German, which changes word lengths and therefore how the digit and gap manipulations read. The questionnaire ran online and unsupervised, so we do not know how long anyone actually spent on the learning page – a participant who read the hard font for twice as long as intended has, in effect, undone the manipulation. And the memory test was scored by hand from free-text answers.</p>
</section>
<section id="data" class="level1">
<h1>Data</h1>
<p>The anonymised responses behind every figure and table on this page are in <a href="https://github.com/schulte-mecklenbeck/web20/blob/main/0_data/BAFS2025_public.csv"><code>BAFS2025_public.csv</code></a>. Gender, age and education are held back and are not published.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Michael Schulte-Mecklenbeck</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>