---
title: "Priority Heuristic comment"
author: "MSM"
date: "2008-03-17"
categories: [Heuristics]
---

We [Johnson, Schulte-Mecklenbeck, & Willemsen, 2008](https://doi.org/10.1037/0033-295X.115.1.263) have got a new paper out that comments on the Priority Heuristic as described in Brandstaetter, Gigerenzer and Hertwig, 2006. 

Resolution of debates in cognition usually comes from the introduction of constraints in the form of ne3, in contrast, has relied predominantly on testing models by examining their fit to choices. The authors examine a recently proposed choice strategy, the priority heuristic, which provides a novel account of how people make risky choices. The authors identify a number of properties that the priority heuristic should have as a process model and illustrate how they may be tested. The results, along with prior research, suggest that although the priority heuristic captures some variability in the attention paid to outcomes, it fails to account for major characteristics of the data, particularly the frequent transitions between outcomes and their probabilities. The article concludes with a discussion of the properties that should be captured by process models of risky choice and the role of process data in theory development.
