---
title: resinstalling packages in R after update
date: 2011-04-14T23:15:45-07:00
author: Michael
categories:
  - R
---
This is old - by should still work :) - comment on how to do this in 2019 below ...

The new version 2.13.0 of [R](http://www.r-project.org/ "R") has just been released and with the update comes the pain of re-installing all the packages from the old installation on the new one.

[Stackoverflow](http://stackoverflow.com/ "Stackoverflow") to the rescue! This [posting](http://stackoverflow.com/questions/1401904/painless-way-to-install-a-new-version-of-r) provides a simple two step process of first writing a list of packages into a file on the disk in the old version, installing the new version and then comparing the exported list to the currently installed packages in the new version with setdiff. I just went through the process and have to say that it is deadeasy! Below the code:

 
1. run in the old version of R

```
packages <- installed.packages()[,"Package"] 
save(packages, file="Rpackages") `
```

2. Install new R version
3. run in the new version

```
load("Rpackages")
for (p in setdiff(packages, installed.packages()[,"Package"]))
install.packages(p)
```

At the end of the day this is outdated - with the new RStudio version you can simply add your packages with `library()` and then simply click on `install packages` in the RStudio interface. 
