---
title: Three weeks without email
date: 2016-01-10T04:34:43-07:00
author: Michael
categories:
  - Lifehacks
---
I spend a lot of time writing and answering email. Email is, according to [timing](http://timingapp.com), the third longest activity on my computer (although I am using three computers and can check this only on one of them &#8211; #timing please let us link computers for an overall analysis) &#8230; anyway &#8211; back to no email &#8211; as a holiday treat I decided to shut down all my email accounts 5 days before Dec. 24th and promised myself not to touch them until Jan. 11th. It turns out that I will come short one day of this plan. Nevertheless, I am quite happy with the result and the positive effects of this email absence. Needless to say that reading emails during vacation brings you back into a working mood (or never lets you out of it), not reading email had positive side effects before (I did this twice in the last 20 years of &#8216;doing&#8217; emails). Many issues that come during such a break often solve themselves without intervention or can be solved quickly within a few hours after being back in the email world.

Well, I will turn on my email accounts now and see how much work has piled up &#8230; BRB.

So, 380 emails later &#8211; a paper submitted by a co-author, a rejection for a previous submission, a talk accepted, a chapter revised by a co-author &#8211; the best part of all this is that dealing with a ton of mails is a very quick thing, with a relatively low threshold for simply deleting out of date emails or replying quickly to urgent matters. What&#8217;s left are some longer replies I will do now &#8230;

Happy New Year!