---
title: 'Eye-Tracking with N > 1'
date: 2017-03-13T12:20:52-07:00
author: Michael
categories:
  - Eye tracking
  - Methods
  - Open Source
  - R
  - Statistics
---
This is one of the fastest papers I have ever written. It was a great collaboration with [Tomás Lejarraga](http://www.uib.eu/personal/ABjI1MDg3Mw/) from the Universitat de les Illes Balears. Why was it great? Because it is one of the rare cases (at least in my academic life) where all people involved in a project contribute equally and quickly. Often, the weight of a contribution lies with one person which slows down things &#8211; with Tomás this was different &#8211; we were often sitting in front of a computer writing together (have never done this before, thought it would not work). Surprisingly this collaborative writing worked out very well and we had the skeleton of the paper within an afternoon. This was followed by many hours of tuning and tacking turns &#8211; but in principle we wrote the most important parts together &#8211; which was pretty cool.

Even cooler &#8211; you can do eye-tracking in groups, using our code.

Here is the [[PDF](/uploads//2009/05/Lejarraga2016.pdf)] and abstract:

The recent introduction of inexpensive eye-trackers has opened up a wealth of opportunities for researchers to study attention in interactive tasks. No software package was previously available to help researchers exploit those opportunities. We created “the pyeTribe”, a software package that offers, among others, the following features: First, a communication platform between many eye-trackers to allow simultaneous recording of multiple participants. Second, the simultaneous calibration of multiple eye-trackers without the experimenter’s supervision. Third, data collection restricted to periods of interest, thus reducing the volume of data and easing analysis. We used a standard economic game (the public goods game) to examine data quality and demonstrate the potential of our software package. Moreover, we conducted a modeling analysis, which illustrates how combining process and behavioral data can improve models of human decision making behavior in social situations. Our software is open source and can thus be used and improved by others.

&nbsp;