---
title: A letter to the black goat
date: 2018-07-30T21:16:40-07:00
author: Michael
categories: [Open science, Replication]
---
I wrote this letter to [the black goat](http://www.theblackgoatpodcast.com/) podcast &#8230; will update here if I hear back from them &#8230;

&nbsp;

Dear goaters (is this a good way to address the three of you?),

<div>
</div>

<div>
  I attended SIPS some weeks ago (first timer). I was unsure what to expect but got a lot of bang for my buck (which is great) &#8211; as a side note I would recommend first timers to try to go there with a concrete project or question or problem, I think there is a good chance to find people with similar issues interested in collaborations.
</div>

<div>
</div>

<div>
  Here is an observation I would be interested to hear your thoughts on: in the SIPS world everything seems to be really straight forward &#8211; we want to &#8216;unfuck psych science&#8217; (Lindsay, 2018), we want to pre-reg studies, upload data, learn R, comment on code, accelerate science, ‘do it right this time’, collaborate, respect, be inclusive (I really learned a lot in that regard listening to your podcast and talking to people at SIPS) …
</div>

<div>
  All of that is great. I subscribe to all of these points.
</div>

<div>
</div>

<div>
  Here is the twist &#8211; people @SIPS talk about &#8216;a movement’  (something that seems very American to me), maybe a movement is needed; people @SIPS talk about ‘a revolution’ &#8211; again, great! obviously there is a need to rattle the cage and accelerate things beyond ‘paradigm shifts at funerals’ (Planck?)
</div>

<div>
  BUT
</div>

<div>
  What happens if you go ‘Outside the SIPS Bubble&#8217; (OSIPSB)?
</div>

<div>
  I have no data (other than my own experiences) but I wonder whether the world (psychology, other sciences) is actually that ready, that willing and open to adopt to these new standards and to actually make a paradigm shift in how we do science. I work at a business school (consumer psych and JDM) there is a lot of finger pointing going on toward psychology (I have a similar feeling that within psychology there is a lot of finger pointing toward social psych) &#8211; &#8216;this is clearly a problem of psychologists but not of us [economists, consumer psychologists, business, accounting researchers &#8230;]’.
</div>

<div>
  Another OSIPSB experience I had was talking to an Action Editor of the Journal of Consumer Psychology (JCR) last year &#8211; we got into a heated debate about the most basic issues, eg, sharing data, pre-reg studies …
</div>

<div>
</div>

<div>
  Is this an observation you share? What would be good steps to address these issues? Should we talk about this within SIPS to get a better balance between enthusiasm and real world requirements (eg hiring decisions are still made mostly by senior faculty, assuming my observation hold, less interested in replication than ’new and exciting effects’ (quote anonymous senior AE of JCR).
</div>

<div>
</div>

<div>
  Thanks for your thoughts!
</div>

<div>
</div>

<div>
</div>

UPDATE in 2019 - on my way to SIPS2019, casually started listening to some podcasts - and then this: https://www.podbean.com/ew/pb-2iqpx-b6aa1e
